spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:stock
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

  redis:
    host: localhost
    port: 6379

logging:
  level:
    it.numble.toss: DEBUG

jwt:
  header: Authorization
  # HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  # echo 'stock-api-server-with-spring-boot-stock-api-server-with-spring-boot'|base64
  secret: c3RvY2stYXBpLXNlcnZlci13aXRoLXNwcmluZy1ib290LXN0b2NrLWFwaS1zZXJ2ZXItd2l0aC1zcHJpbmctYm9vdA==
  # expire time : 24 Hour
  token-validity-in-seconds-atk: 7200
  token-validity-in-seconds-rtk: 604800

